// File: ALU.v
// Generated by MyHDL 0.11
// Date: Mon Jun  7 23:28:07 2021


`timescale 1ns/10ps

module ALU (
    result,
    input_1,
    input_2,
    sel
);


output [7:0] result;
reg [7:0] result;
input [7:0] input_1;
input [7:0] input_2;
input [3:0] sel;




always @(sel, input_2, input_1) begin: ALU_ALU_MUX
    case (sel)
        'h1: begin
            result = (input_1 + input_2);
        end
        'h2: begin
            result = (input_2 - input_1);
        end
        'h3: begin
            result = (input_1 & input_2);
        end
        'h4: begin
            result = (input_1 | input_2);
        end
        'h5: begin
            result = (input_1 ^ input_2);
        end
        default: begin
            result = 0;
        end
    endcase
end

endmodule
