// File: barrel_shifter.v
// Generated by MyHDL 0.11
// Date: Mon Jun  7 21:08:52 2021


`timescale 1ns/10ps

module barrel_shifter (
    load_reg,
    load_in,
    shift
);


output [11:0] load_reg;
wire [11:0] load_reg;
input [11:0] load_in;
input [2:0] shift;





assign load_reg = (load_in >>> shift);

endmodule
