// File: Decoder.v
// Generated by MyHDL 0.11
// Date: Mon Jun  7 21:27:21 2021


`timescale 1ns/10ps

module Decoder (
    out,
    inp
);


output [15:0] out;
reg [15:0] out;
input [3:0] inp;




always @(inp) begin: DECODER_DECODER
    out = 0;
    out[inp] = 1;
end

endmodule
