// File: ParallelReg.v
// Generated by MyHDL 0.11
// Date: Sat Jun  5 22:16:07 2021


`timescale 1ns/10ps

module ParallelReg (
    out,
    inp,
    clock,
    enable,
    reset
);


output [31:0] out;
reg [31:0] out;
input [31:0] inp;
input clock;
input enable;
input reset;




always @(posedge clock) begin: PARALLELREG_PASSIT
    if (reset == 0) begin
        out <= 0;
    end
    else begin
        if (enable) begin
            out <= inp;
        end
    end
end

endmodule
