// File: SimpleMemory1.v
// Generated by MyHDL 0.11
// Date: Mon Jun  7 21:07:35 2021


`timescale 1ns/10ps

module SimpleMemory1 (
    clk,
    w_enable,
    w_r_address,
    input_data,
    output_data
);
// A simple memory made of 32 -8-bit registers.
// :param clk: Clock signal
// :param w_enable: Write enable signal
// :param w_r_address: Address to write or read from
// :param input_data: Data input
// :param output_data: Data output

input clk;
input w_enable;
input [4:0] w_r_address;
input [7:0] input_data;
output [7:0] output_data;
wire [7:0] output_data;

reg [7:0] memory1 [0:32-1];



always @(posedge clk) begin: SIMPLEMEMORY1_WRITE_DATA
    if (w_enable) begin
        memory1[w_r_address] <= input_data;
    end
end



assign output_data = memory1[w_r_address];

endmodule
